### ISSUE TITLE
Single GPU Training

### ISSUE THREAD

**Issue by nixczhou** [facebookresearch/simsiam#30]
In the readme, it stated that,

Only multi-gpu, DistributedDataParallel training is supported; single-gpu or DataParallel training is not supported.

But when I saw the code, i think we can choose to not using DistributedDataParallel, does using the single gpu will affect any performance?

**Comment by endernewton** [comment]
Single GPU training is possible and doable for debugging. You can just comment that line (https://github.com/facebookresearch/simsiam/blob/main/main_simsiam.py#L183) so it does not raise an error.

Single GPU affects performance mainly due to batch size -- cannot fit many images into one single GPU. Otherwise if you manage to train on single GPU, let me know!

**Comment by nixczhou** [comment]
Just curious,  small Batch Size like 64 ~ 256 does not matter for the SimSiam model , isn't it?

**Comment by dikapiliao1** [comment]
Can you train with a single GPU？
